[ClassVersion("1.0.0"), FriendlyName("GitSync")]
class GitSync : OMI_BaseResource
{
    [Key] string GitRepositoryUrl;
    [Required] string LocalPath;
    [Required] string Branch;
    [Write, EmbeddedInstance("MSFT_Credential")] string Credential;
    [Required, ValueMap{"token", "basic", "none"}, Values{"token", "basic", "none"}] string AuthType;
    [Write, ValueMap{"true", "false"}, Values{"true", "false"}] boolean ForceSync;
};